# Generated by Django 3.1.7 on 2021-03-31 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('project_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
